openapi: 3.2.0
info:
  title: SERTICA Web Device API
  description: 'Online API browser for SERTICA Web API.


    Be aware that some endpoints are restricted by license or user rights and may not be available in your environment.


    Each endpoint includes a description of the required license and user rights.'
  version: v1
servers:
- url: /api
tags:
- name: Device
paths:
  /Device/confirm:
    post:
      tags:
      - Device
      operationId: ConfirmData
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.ForDeviceRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.ForDeviceRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.ForDeviceRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.ForDeviceRequest'
      responses:
        '200':
          description: OK
        '401':
          description: If user is unauthorized
        '500':
          description: The api has encountered an unhandled exception. See Sertica logs for details
      security:
      - Bearer: []
      summary: Confirm data
      x-summary-source: derived
components:
  schemas:
    Logihold.BusinessObjects.LogiholdObjModel.Search.ForDeviceRequest:
      type: object
      properties:
        deviceGuid:
          type:
          - string
          - 'null'
          format: uuid
        requestIdGuid:
          type:
          - string
          - 'null'
          format: uuid
        fullSynchronization:
          type: boolean
        appType:
          type: integer
          format: int32
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: JWT Authorization header using the Bearer scheme
      scheme: bearer
