openapi: 3.2.0
info:
  title: SERTICA Web External Calendars API
  description: 'Online API browser for SERTICA Web API.


    Be aware that some endpoints are restricted by license or user rights and may not be available in your environment.


    Each endpoint includes a description of the required license and user rights.'
  version: v1
servers:
- url: /api
tags:
- name: ExternalCalendars
paths:
  /ExternalCalendars/search:
    post:
      tags:
      - ExternalCalendars
      summary: Returns an array of ApiWebhookExecuteResult by executing all active…
      operationId: Search
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SerticaWebApi.Models.Webhooks.ApiWebhookExecuteResult'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SerticaWebApi.Models.Webhooks.ApiWebhookExecuteResult'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SerticaWebApi.Models.Webhooks.ApiWebhookExecuteResult'
        '404':
          description: Not Found
        '401':
          description: If user is unauthorized
        '403':
          description: User must have one of these User Rights</br><table><thead><tr><th>Key</th><th>Right</th></tr></thead><tbody><tr><td style='border-bottom:none;padding-right:5px'>ReadExternalCalendar</td><td style='border-bottom:none'>Function</td></tr></tbody></table>
        '500':
          description: The api has encountered an unhandled exception. See Sertica logs for details
      security:
      - Bearer: []
components:
  schemas:
    SerticaWebApi.Models.Webhooks.ApiWebhookExecuteResult:
      type: object
      properties:
        success:
          type: boolean
        message:
          type:
          - string
          - 'null'
        webhookNo:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: JWT Authorization header using the Bearer scheme
      scheme: bearer
