openapi: 3.2.0
info:
  title: SERTICA Web Ios Data Sync API
  description: 'Online API browser for SERTICA Web API.


    Be aware that some endpoints are restricted by license or user rights and may not be available in your environment.


    Each endpoint includes a description of the required license and user rights.'
  version: v1
servers:
- url: /api
tags:
- name: IosDataSync
paths:
  /IosDataSync/ResetObjectIosDataSync:
    post:
      tags:
      - IosDataSync
      operationId: ResetObjectIosDataSync
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/SerticaWebApi.Models.Framework.IosDataSyncResetObject'
          application/json:
            schema:
              $ref: '#/components/schemas/SerticaWebApi.Models.Framework.IosDataSyncResetObject'
          text/json:
            schema:
              $ref: '#/components/schemas/SerticaWebApi.Models.Framework.IosDataSyncResetObject'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SerticaWebApi.Models.Framework.IosDataSyncResetObject'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SerticaWebApi.Models.Framework.IosDataSyncResetObject'
            application/json:
              schema:
                $ref: '#/components/schemas/SerticaWebApi.Models.Framework.IosDataSyncResetObject'
            text/json:
              schema:
                $ref: '#/components/schemas/SerticaWebApi.Models.Framework.IosDataSyncResetObject'
        '401':
          description: If user is unauthorized
        '403':
          description: User must have one of these User Rights</br><table><thead><tr><th>Key</th><th>Right</th></tr></thead><tbody><tr><td style='border-bottom:none;padding-right:5px'>JobApp</td><td style='border-bottom:none'>Function</td></tr></tbody></table>
        '500':
          description: The api has encountered an unhandled exception. See Sertica logs for details
      security:
      - Bearer: []
      summary: Reset object ios data sync
      x-summary-source: derived
components:
  schemas:
    SerticaWebApi.Models.Framework.IosDataSyncResetObject:
      type: object
      properties:
        deviceGuid:
          type:
          - string
          - 'null'
        objectGuids:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: JWT Authorization header using the Bearer scheme
      scheme: bearer
