openapi: 3.2.0
info:
  title: SERTICA Web Transaction Queue API
  description: 'Online API browser for SERTICA Web API.


    Be aware that some endpoints are restricted by license or user rights and may not be available in your environment.


    Each endpoint includes a description of the required license and user rights.'
  version: v1
servers:
- url: /api
tags:
- name: TransactionQueue
paths:
  /TransactionQueue/search:
    post:
      tags:
      - TransactionQueue
      summary: Search for items in Transaction Queue Takes a SearchDefinition input, which can…
      operationId: SearchTransactionQueue
      parameters:
      - name: page
        in: query
        description: Page
        schema:
          type: integer
          format: int32
          default: 1
      - name: pageSize
        in: query
        description: Pagesize
        schema:
          type: integer
          format: int32
          default: 25
      requestBody:
        description: The search definition
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
          application/json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
          text/json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SerticaWebApi.Models.Transactions.TransactionQueue'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SerticaWebApi.Models.Transactions.TransactionQueue'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SerticaWebApi.Models.Transactions.TransactionQueue'
        '401':
          description: If user is unauthorized
        '403':
          description: User must have one of these User Rights</br><table><thead><tr><th>Key</th><th>Right</th></tr></thead><tbody><tr><td style='border-bottom:none;padding-right:5px'>DataTransaction</td><td style='border-bottom:none'>View</td></tr></tbody></table>
        '500':
          description: The api has encountered an unhandled exception. See Sertica logs for details
      security:
      - Bearer: []
  /TransactionQueue/searchInfo:
    get:
      tags:
      - TransactionQueue
      summary: Returns structured information about what and how you can search for
      operationId: SearchInfoTransactionQueue
      responses:
        '200':
          description: Returns a list of valid search fields
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchInfo'
            application/json:
              schema:
                $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchInfo'
            text/json:
              schema:
                $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchInfo'
        '500':
          description: The api has encountered an unhandled exception. See Sertica logs for details
  /TransactionQueue/searchCount:
    post:
      tags:
      - TransactionQueue
      summary: Returns number Takes a SearchDefinition input, which can include filters and…
      operationId: SearchCountTransactionQueue
      requestBody:
        description: The search definition
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
          application/json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
          text/json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: integer
                format: int32
            application/json:
              schema:
                type: integer
                format: int32
            text/json:
              schema:
                type: integer
                format: int32
        '401':
          description: If user is unauthorized
        '403':
          description: User must have one of these User Rights</br><table><thead><tr><th>Key</th><th>Right</th></tr></thead><tbody><tr><td style='border-bottom:none;padding-right:5px'>DataTransaction</td><td style='border-bottom:none'>View</td></tr></tbody></table>
        '500':
          description: The api has encountered an unhandled exception. See Sertica logs for details
      security:
      - Bearer: []
  /TransactionQueue/searchIndex/{transactionQueueGuid}:
    post:
      tags:
      - TransactionQueue
      summary: Get index of a record in a search for item in the Transaction Queue Takes a…
      operationId: SearchTransactionQueueIndex
      parameters:
      - name: transactionQueueGuid
        in: path
        description: The data transaction to get index for
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        description: The search definition
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
          application/json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
          text/json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: integer
                format: int32
            application/json:
              schema:
                type: integer
                format: int32
            text/json:
              schema:
                type: integer
                format: int32
        '401':
          description: If user is unauthorized
        '403':
          description: User must have one of these User Rights</br><table><thead><tr><th>Key</th><th>Right</th></tr></thead><tbody><tr><td style='border-bottom:none;padding-right:5px'>DataTransaction</td><td style='border-bottom:none'>View</td></tr></tbody></table>
        '500':
          description: The api has encountered an unhandled exception. See Sertica logs for details
      security:
      - Bearer: []
components:
  schemas:
    Logihold.BusinessObjects.LogiholdObjModel.Search.ForDeviceRequest:
      type: object
      properties:
        deviceGuid:
          type:
          - string
          - 'null'
          format: uuid
        requestIdGuid:
          type:
          - string
          - 'null'
          format: uuid
        fullSynchronization:
          type: boolean
        appType:
          type: integer
          format: int32
      additionalProperties: false
    Logihold.BusinessObjects.LogiholdObjModel.Search.SearchInfoField:
      type: object
      properties:
        field:
          type:
          - string
          - 'null'
        dataType:
          $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDataType'
        operators:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchOperator'
        enumType:
          type:
          - string
          - 'null'
        isCustomProperty:
          type: boolean
      additionalProperties: false
    Logihold.BusinessObjects.LogiholdObjModel.View.SortDirection:
      enum:
      - Asc
      - Desc
      type: string
    SerticaWebApi.Models.Transactions.TransactionQueue:
      type: object
      properties:
        idSeq:
          type:
          - string
          - 'null'
        objectGUID:
          type:
          - string
          - 'null'
        objectTable:
          type:
          - string
          - 'null'
        typeName:
          type:
          - string
          - 'null'
        versionNo:
          type:
          - string
          - 'null'
        objectLiveGuid:
          type:
          - string
          - 'null'
        updateUserNo:
          type:
          - string
          - 'null'
        updateUserName:
          type:
          - string
          - 'null'
        updateDate:
          type:
          - string
          - 'null'
          format: date-time
        createUserNo:
          type:
          - string
          - 'null'
        createUserName:
          type:
          - string
          - 'null'
        createDate:
          type:
          - string
          - 'null'
          format: date-time
        latestHistoryGuid:
          type:
          - string
          - 'null'
          format: uuid
        unitNo:
          type:
          - string
          - 'null'
        unitName:
          type:
          - string
          - 'null'
        guid:
          type:
          - string
          - 'null'
          format: uuid
        liveObjectGuid:
          type:
          - string
          - 'null'
          format: uuid
        unitGuid:
          type:
          - string
          - 'null'
          format: uuid
        deleted:
          type: boolean
        links:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SerticaWebApi.Models.Link'
          readOnly: true
      additionalProperties: false
    SerticaWebApi.Models.Link:
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        url:
          type:
          - string
          - 'null'
      additionalProperties: false
    Logihold.BusinessObjects.LogiholdObjModel.Search.SearchOperator:
      enum:
      - Equals
      - LessThan
      - GreaterThan
      - Like
      - Range
      - In
      - Dynamic
      - StartsWith
      - EndsWith
      - IsNull
      - NotLike
      - Or
      - NotEquals
      - NotIn
      type: string
    Logihold.BusinessObjects.LogiholdObjModel.Search.OrderBy:
      type: object
      properties:
        field:
          type:
          - string
          - 'null'
        direction:
          $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.View.SortDirection'
      additionalProperties: false
    Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDataType:
      enum:
      - Unkonwn
      - String
      - Int
      - Decimal
      - Enum
      - DateTime
      - Guid
      - Bool
      - Duration
      type: string
    Logihold.BusinessObjects.LogiholdObjModel.Search.ValuesMatching:
      enum:
      - All
      - One
      type: string
    Logihold.BusinessObjects.LogiholdObjModel.Search.SearchDefinition:
      type: object
      properties:
        distinct:
          type: boolean
        subObjectsToInclude:
          type:
          - array
          - 'null'
          items:
            type: string
        contains:
          type:
          - array
          - 'null'
          items:
            type: string
        criteria:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchCriteria'
        sorting:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.OrderBy'
        columns:
          type:
          - array
          - 'null'
          items:
            type: string
        forDeviceRequest:
          $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.ForDeviceRequest'
        unitFilter:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    Logihold.BusinessObjects.LogiholdObjModel.Search.SearchInfo:
      type: object
      properties:
        supportsContains:
          type: boolean
        fields:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchInfoField'
          readOnly: true
      additionalProperties: false
    Logihold.BusinessObjects.LogiholdObjModel.Search.SearchCriteria:
      type: object
      properties:
        field:
          type:
          - string
          - 'null'
        operator:
          $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.SearchOperator'
        values:
          type:
          - array
          - 'null'
          items: {}
        valuesMatching:
          $ref: '#/components/schemas/Logihold.BusinessObjects.LogiholdObjModel.Search.ValuesMatching'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: JWT Authorization header using the Bearer scheme
      scheme: bearer
