openapi: 3.2.0
info:
  title: SERTICA Web Electronic Logbook API
  description: 'Online API browser for SERTICA Web API.


    Be aware that some endpoints are restricted by license or user rights and may not be available in your environment.


    Each endpoint includes a description of the required license and user rights.'
  version: v1
servers:
- url: /api
tags:
- name: ElectronicLogbook
paths:
  /ElectronicLogbook/SetupSLB:
    post:
      tags:
      - ElectronicLogbook
      operationId: SetupSLBForProduction
      responses:
        '200':
          description: OK
        '401':
          description: If user is unauthorized
        '403':
          description: User must have one of these User Rights</br><table><thead><tr><th>Key</th><th>Right</th></tr></thead><tbody><tr><td style='border-bottom:none;padding-right:5px'>Substance_Update</td><td style='border-bottom:none'>Update</td></tr><tr><td style='border-bottom:none;padding-right:5px'>LubeOilType_Update</td><td style='border-bottom:none'>Update</td></tr><tr><td style='border-bottom:none;padding-right:5px'>FuelType_Update</td><td style='border-bottom:none'>Update</td></tr><tr><td style='border-bottom:none;padding-right:5px'>LiquidType_Update</td><td style='border-bottom:none'>Update</td></tr></tbody></table><br/><br/>Customer must have one of these License values set<table><thead><tr><th>Key</th><th>Right</th></tr></thead><tbody><tr><td style='border-bottom:none;padding-right:5px'>ElectronicLogbook</td></tr></tbody></table>
        '500':
          description: The api has encountered an unhandled exception. See Sertica logs for details
      security:
      - Bearer: []
      summary: Setup SLB for production
      x-summary-source: derived
components:
  securitySchemes:
    Bearer:
      type: http
      description: JWT Authorization header using the Bearer scheme
      scheme: bearer
